// Services/AuthService.cs
using Microsoft.EntityFrameworkCore;
using GameRealmAPI.Data;
using GameRealmAPI.DTOs;
using GameRealmAPI.Helpers;
using GameRealmAPI.Models;

namespace GameRealmAPI.Services;

public class AuthService
{
    private readonly AppDbContext _db;
    private readonly JwtHelper _jwt;
    private readonly EmailService _email;

    public AuthService(AppDbContext db, JwtHelper jwt, EmailService email)
    {
        _db = db;
        _jwt = jwt;
        _email = email;
    }

    // ===== REGISTER =====
    public async Task<ApiResponse<AuthResponse>> RegisterAsync(RegisterRequest req)
    {
        if (string.IsNullOrWhiteSpace(req.Username) || req.Username.Length < 3)
            return Fail<AuthResponse>("Username must be at least 3 characters");

        if (req.Password.Length < 6)
            return Fail<AuthResponse>("Password must be at least 6 characters");

        if (!req.Email.Contains('@'))
            return Fail<AuthResponse>("Invalid email address");

        var exists = await _db.Users.AnyAsync(u => u.Username == req.Username);
        if (exists)
            return Fail<AuthResponse>("Username already taken");

        var strategy = _db.Database.CreateExecutionStrategy();
        return await strategy.ExecuteAsync(async () =>
        {
            using var transaction = await _db.Database.BeginTransactionAsync();
            try
            {
                var user = new User
                {
                    // Id will be generated by MySQL and retrieved by EF via ValueGeneratedOnAdd
                    Username = req.Username.Trim(),
                    Email    = req.Email.ToLower().Trim(),
                    Password = req.Password,
                    Role     = AccountRole.Player,
                    CreatedAt = DateTime.UtcNow,
                    IsActive = true
                };

                _db.Users.Add(user);
                await _db.SaveChangesAsync();

                // Player creation logic removed - game server will handle it

                await transaction.CommitAsync();

                var (token, expiresAt) = _jwt.GenerateToken(user);
                return Ok("Account created successfully", new AuthResponse(token, expiresAt, ToDto(user)));
            }
            catch (Exception ex)
            {
                await transaction.RollbackAsync();
                return Fail<AuthResponse>($"Registration failed: {ex.Message}");
            }
        });
    }

    // ===== LOGIN =====
    public async Task<ApiResponse<AuthResponse>> LoginAsync(LoginRequest req)
    {
        const string genericError = "Invalid username or password";

        var user = await AppDbContext.GetUserByEmailOrUsername(_db, req.Username.ToLower());

        if (user == null || user.Password != req.Password)
            return Fail<AuthResponse>(genericError);

        if (user.IsBanned == true)
            return Fail<AuthResponse>("Account is banned. Contact support.");

        var tracked = await _db.Users.AsTracking().FirstAsync(u => u.Id == user.Id);
        tracked.LastLoginAt = DateTime.UtcNow;
        await _db.SaveChangesAsync();

        var (token, expiresAt) = _jwt.GenerateToken(user);
        return Ok("Login successful", new AuthResponse(token, expiresAt, ToDto(user)));
    }

    // ===== FORGOT PASSWORD =====
    public async Task<ApiResponse> ForgotPasswordAsync(string email)
    {
        const string safe = "If this email exists, a reset link has been sent";

        var user = await _db.Users.AsTracking()
            .FirstOrDefaultAsync(u => u.Email == email.ToLower());

        if (user == null) return new ApiResponse(true, safe);

        user.ResetToken = Guid.NewGuid().ToString("N");
        user.ResetTokenExpiry = DateTime.UtcNow.AddHours(2);
        await _db.SaveChangesAsync();

        await _email.SendPasswordResetAsync(user.Email, user.Username, user.ResetToken);
        return new ApiResponse(true, safe);
    }

    // ===== CHANGE PASSWORD =====
    public async Task<ApiResponse> ChangePasswordAsync(int userId, ChangePasswordRequest req)
    {
        var user = await _db.Users.AsTracking().FirstOrDefaultAsync(u => u.Id == userId);
        if (user == null) return new ApiResponse(false, "User not found");

        if (user.Password != req.CurrentPassword)
            return new ApiResponse(false, "Current password is incorrect");

        user.Password = req.NewPassword;
        await _db.SaveChangesAsync();
        return new ApiResponse(true, "Password changed successfully");
    }

    // ===== RESET PASSWORD =====
    public async Task<ApiResponse> ResetPasswordAsync(ResetPasswordRequest req)
    {
        var user = await _db.Users.AsTracking()
            .FirstOrDefaultAsync(u =>
                u.ResetToken == req.Token &&
                u.ResetTokenExpiry > DateTime.UtcNow);

        if (user == null) return new ApiResponse(false, "Invalid or expired reset token");

        user.Password = req.NewPassword;
        user.ResetToken = null;
        user.ResetTokenExpiry = null;
        await _db.SaveChangesAsync();
        return new ApiResponse(true, "Password reset successfully");
    }

    // ===== HELPERS =====
    private static ApiResponse<T> Ok<T>(string msg, T data) => new(true, msg, data);
    private static ApiResponse<T> Fail<T>(string msg) => new(false, msg);
    private static UserDto ToDto(User u) => new(u.Id, u.Username, u.Email, u.RoleName, u.CreatedAt);
}

